[theme]
primaryColor              = "#0B2545"
backgroundColor           = "#F7F9FC"
secondaryBackgroundColor  = "#EEF2F7"
textColor                 = "#111827"
font                      = "sans serif"

[server]
headless             = true
enableCORS           = true
enableXsrfProtection = true

[browser]
gatherUsageStats = false
