[theme]
primaryColor              = "#0B2545"
backgroundColor           = "#F4F6FA"
secondaryBackgroundColor  = "#EAEEF5"
textColor                 = "#111827"
font                      = "sans serif"

[server]
headless             = true
enableCORS           = true
enableXsrfProtection = true
maxUploadSize        = 10

[browser]
gatherUsageStats = false

[runner]
fastReruns = true

[client]
showSidebarNavigation = true
